#The developer badge
print ("          Developer Badge")
print("***********************************")
print("*                                 *")
print("*         DEVELOPER ID BADGE      *")
print("*         _________________       *")   
print("*                                 *")
print("*      Name:    John Doe          *")
print("*      ID:      123456789         *")
print("*      Email: john.doe@example.com*")
print("***********************************")