print("Mother")
print("It takes a special kind of someone")
print("To turn a house into a home,")
print ("To grow a boy into a man,")
print("In blood, in flesh and bone.")
print()
print("To fill his mind with knowledge,")
print("The kind that colleges have never known;")
print("And instill his heart with love,")
print ("So that he can better make his own.")
print()
print("It takes a special kind of someone")
print("To be there all the while__")
print("Just to see you her rising son")
print("Through every tear, and every smile.")
print()
print("TO be there through the years,")
print("Through every fear, and every trail;")
print("That someone is a mother...")
print("That someone is my mother.")